version: "3.8"
services:
  development:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file: 
      - ./.env
    volumes:
      - ./src:/usr/app/src