FROM node:16 as rede-athis-react-build

WORKDIR /usr/app

COPY package.json .
RUN npm install --legacy-peer-deps 

COPY . . 

RUN npm run build

FROM nginx

COPY --from=rede-athis-react-build /usr/app/build /usr/share/nginx/html